import {
  DocLayout,
  DocList,
  DocNote,
  DocTable,
  DocCode,
  type DocSection,
} from '@/components/docs/doc-layout';

const sections: DocSection[] = [
  {
    id: 'overview',
    heading: 'Platform overview',
    body: (
      <>
        <p>
          Revo Treasury is an AI-assisted treasury console on the <strong>Arc Testnet</strong>{' '}
          (chain 5042002). Each operator wallet owns a private treasury. Arcus, the treasury
          agent, turns natural-language strategy into validated proposals, and every mutation
          passes through security controls before it touches state.
        </p>
        <p>The system has three planes:</p>
        <DocList
          items={[
            <>
              <strong>Identity plane.</strong> Wallet-signature authentication; a session binds
              you to exactly one treasury.
            </>,
            <>
              <strong>Decision plane.</strong> Commands, proposals, policies, and approvals:
              the human-plus-agent workflow.
            </>,
            <>
              <strong>Settlement plane.</strong> Per-treasury custody wallets that move testnet
              USDC on-chain for deposits and withdrawals.
            </>,
          ]}
        />
      </>
    ),
  },
  {
    id: 'getting-started',
    heading: 'Getting started',
    body: (
      <>
        <p>Access takes three steps and roughly a minute:</p>
        <DocList
          items={[
            <>
              <strong>01: Connect a wallet.</strong> Any injected browser wallet is detected
              automatically (EIP-6963). No extension-specific setup.
            </>,
            <>
              <strong>02: Switch to Arc Testnet.</strong> The console offers the network switch
              (chain 5042002) if your wallet is elsewhere.
            </>,
            <>
              <strong>03: Verify ownership.</strong> Sign a one-time message. The signature
              proves control of the address; it costs no gas and authorizes no transfers.
            </>,
          ]}
        />
        <DocNote label="First sign-in">
          A first-time wallet is provisioned its own private treasury automatically and receives
          the administrator role. Treasuries start empty. Every number you see afterwards is a
          consequence of your own deposits and decisions.
        </DocNote>
      </>
    ),
  },
  {
    id: 'arcus',
    heading: 'Arcus: the treasury agent',
    body: (
      <>
        <p>
          Arcus accepts plain-language input in two forms:
        </p>
        <DocList
          items={[
            <>
              <strong>Commands</strong>, "rotate 20% of idle USDC into staked yield," are
              compiled into structured proposals with allocation math, risk framing, and guardrail
              checks. Nothing executes without passing the approval workflow.
            </>,
            <>
              <strong>Questions</strong>, "what is our current drawdown exposure?", are answered
              from live treasury context: balances, mode, policies, and recent activity.
            </>,
          ]}
        />
        <p>
          Agent traffic is rate-limited and bounded. Responses are informational tooling, not
          financial advice; the <a href="/risk" className="text-primary hover:underline">Risk
          Disclaimer</a> covers the model's limits.
        </p>
      </>
    ),
  },
  {
    id: 'proposals',
    heading: 'Proposals and approvals',
    body: (
      <>
        <p>
          A proposal is the unit of change: a target allocation with rationale, generated by Arcus
          or by policy. Proposals move through a strict lifecycle: pending review, approved and
          executed, or rejected with a recorded reason.
        </p>
        <DocList
          items={[
            <>Approve/reject actions are atomic: concurrent decisions on the same proposal cannot double-execute.</>,
            <>Execution applies the rebalance to treasury state and writes an activity record.</>,
            <>Every decision lands in the tamper-evident audit log with the acting wallet.</>,
          ]}
        />
      </>
    ),
  },
  {
    id: 'policies',
    heading: 'Policies',
    body: (
      <p>
        Policies are standing rules compiled from natural language, for example, drawdown limits
        or allocation ceilings. A policy moves through <DocCode>draft</DocCode> →{' '}
        <DocCode>active</DocCode> states, can be <DocCode>rejected</DocCode> at review, and is
        marked <DocCode>superseded</DocCode> when a newer policy replaces it. Active policies feed
        the agent's proposal generation and the platform's monitoring jobs.
      </p>
    ),
  },
  {
    id: 'modes',
    heading: 'Operating modes',
    body: (
      <>
        <p>The mode dial sets how much latitude the agent has:</p>
        <DocTable
          head={['Mode', 'Behavior']}
          rows={[
            [
              <DocCode key="m1">safe</DocCode>,
              'Observation only. The agent analyzes and drafts, but nothing moves without an explicit operator decision.',
            ],
            [
              <DocCode key="m2">managed</DocCode>,
              'The agent prepares and queues proposals; operators approve or reject each one.',
            ],
            [
              <DocCode key="m3">autonomous</DocCode>,
              'The agent may act within hard guardrails. Security caps and pause controls still bind every action.',
            ],
          ]}
        />
      </>
    ),
  },
  {
    id: 'funds',
    heading: 'Deposits and withdrawals',
    body: (
      <>
        <p>
          Each treasury has a dedicated deposit address on Arc Testnet, shown in the console's
          wallet panel.
        </p>
        <DocList
          items={[
            <>
              <strong>Deposit.</strong> Send testnet USDC to your treasury address, then submit
              the transaction hash. The transfer is verified against the Arc Testnet RPC before
              being credited; a hash can only ever be credited once, to one treasury.
            </>,
            <>
              <strong>Withdraw.</strong> Request a withdrawal to the depositing wallet and sign a
              time-limited authorization message (valid for five minutes). The treasury sends the
              transfer on-chain; a reconciliation job resolves any transfer interrupted mid-flight.
            </>,
            <>
              <strong>Limits.</strong> Per-withdrawal and daily caps apply, configurable in the
              security panel within platform bounds.
            </>,
          ]}
        />
        <DocNote label="Warning">
          Arc Testnet USDC only. Never send mainnet assets or anything of value; it is
          unrecoverable.
        </DocNote>
      </>
    ),
  },
  {
    id: 'security',
    heading: 'Security controls',
    body: (
      <>
        <DocList
          items={[
            <>
              <strong>Emergency pause.</strong> Freezes treasury mutations instantly; state
              transitions are serialized so a pause cannot race an execution.
            </>,
            <>
              <strong>Withdrawal caps.</strong> Per-transaction and rolling daily limits enforced
              inside the database transaction that moves funds.
            </>,
            <>
              <strong>Audit trail.</strong> Privileged actions are recorded in a hash-chained log;
              retroactive edits are detectable.
            </>,
            <>
              <strong>Risk drills.</strong> A drill simulates an emergency rotation against your
              real balances so you can rehearse operator response. Drills require a funded
              treasury; the platform never fabricates numbers for an empty one.
            </>,
            <>
              <strong>Alerts.</strong> Drawdown breaches and operational anomalies surface in the
              console's alert stream.
            </>,
          ]}
        />
      </>
    ),
  },
  {
    id: 'api',
    heading: 'API reference',
    body: (
      <>
        <p>
          The console is built on a JSON HTTP API rooted at <DocCode>/api</DocCode>.
          Authentication is a wallet-signature exchange that sets an HTTP-only session cookie;
          all treasury routes are scoped to the authenticated operator's treasury; the tenant is
          never taken from client input.
        </p>
        <DocTable
          head={['Method', 'Path', 'Purpose']}
          rows={[
            [<DocCode key="a1">POST</DocCode>, <DocCode key="a2">/auth/nonce</DocCode>, 'Issue a one-time sign-in message for a wallet address.'],
            [<DocCode key="b1">POST</DocCode>, <DocCode key="b2">/auth/verify</DocCode>, 'Verify the signed message; establishes the session.'],
            [<DocCode key="c1">GET</DocCode>, <DocCode key="c2">/auth/me</DocCode>, 'Current operator, role, and treasury.'],
            [<DocCode key="d1">POST</DocCode>, <DocCode key="d2">/auth/logout</DocCode>, 'Invalidate the session.'],
            [<DocCode key="e1">GET</DocCode>, <DocCode key="e2">/treasury/dashboard</DocCode>, 'NAV, allocations, activity, and drill state.'],
            [<DocCode key="f1">POST</DocCode>, <DocCode key="f2">/treasury/command</DocCode>, 'Submit a natural-language strategy for compilation.'],
            [<DocCode key="g1">GET</DocCode>, <DocCode key="g2">/treasury/proposals</DocCode>, 'Proposal queue and history.'],
            [<DocCode key="h1">POST</DocCode>, <DocCode key="h2">/treasury/proposals/:id/approve</DocCode>, 'Approve and execute a pending proposal.'],
            [<DocCode key="i1">POST</DocCode>, <DocCode key="i2">/treasury/proposals/:id/reject</DocCode>, 'Reject a pending proposal with a reason.'],
            [<DocCode key="j1">GET</DocCode>, <DocCode key="j2">/treasury/policies</DocCode>, 'Policy timeline: drafts, active, rejected, superseded.'],
            [<DocCode key="k1">GET/PUT</DocCode>, <DocCode key="k2">/treasury/mode</DocCode>, 'Read or set the operating mode.'],
            [<DocCode key="l1">GET</DocCode>, <DocCode key="l2">/treasury/wallet</DocCode>, 'Treasury deposit address and chain parameters.'],
            [<DocCode key="m1">POST</DocCode>, <DocCode key="m2">/treasury/wallet/deposits</DocCode>, 'Claim a confirmed on-chain deposit by transaction hash.'],
            [<DocCode key="n1">POST</DocCode>, <DocCode key="n2">/treasury/wallet/withdrawals</DocCode>, 'Signature-authorized withdrawal to the depositor wallet.'],
            [<DocCode key="o1">GET</DocCode>, <DocCode key="o2">/treasury/security</DocCode>, 'Security controls: pause state and limits.'],
            [<DocCode key="p1">GET</DocCode>, <DocCode key="p2">/treasury/signals</DocCode>, 'Public market signals feed (elements simulated, labeled).'],
            [<DocCode key="q1">GET</DocCode>, <DocCode key="q2">/chain/status</DocCode>, 'Public Arc Testnet chain status.'],
          ]}
        />
        <p>
          Mutating routes enforce role permissions (administrator, strategist, approver, guardian)
          and return conventional status codes: <DocCode>401</DocCode> unauthenticated,{' '}
          <DocCode>403</DocCode> insufficient role, <DocCode>409</DocCode> state conflict.
        </p>
      </>
    ),
  },
];

export default function Docs() {
  return (
    <DocLayout
      code="RVO-DOC-01"
      title="Documentation"
      tagline="How the Revo Treasury platform works, end to end: identity, the agent workflow, custody of testnet funds, security controls, and the API underneath the console."
      status="CURRENT"
      sections={sections}
    />
  );
}
