import { DocLayout, DocList, DocNote, type DocSection } from '@/components/docs/doc-layout';

const sections: DocSection[] = [
  {
    id: 'scope',
    heading: 'Scope of this policy',
    body: (
      <>
        <p>
          This Privacy Policy describes how <strong>Revo Core Technologies</strong> ("Revo", "we",
          "us") collects, uses, and protects information when you use the Revo Treasury platform,
          the public website, the operator console, and the underlying API (together, the
          "Service"), operating on the Arc Testnet.
        </p>
        <p>
          Revo is designed around a simple principle: <strong>your wallet is your identity</strong>.
          We do not run accounts, mailing lists, or advertising systems, and we collect only what
          the Service needs to function.
        </p>
      </>
    ),
  },
  {
    id: 'information-we-collect',
    heading: 'Information we collect',
    body: (
      <>
        <p>When you use the Service, we process the following categories of data:</p>
        <DocList
          items={[
            <>
              <strong>Wallet address.</strong> The public address you connect and sign in with. It
              identifies your operator session and your treasury.
            </>,
            <>
              <strong>Authentication signatures.</strong> The one-time nonce we issue and the
              signed message you return to prove wallet ownership. Signatures authorize nothing
              beyond sign-in.
            </>,
            <>
              <strong>Session data.</strong> A single session cookie that keeps you signed in, with
              its creation and expiry timestamps.
            </>,
            <>
              <strong>Treasury records.</strong> Proposals, policies, activity history, security
              settings, alerts, and audit events generated by your use of the console.
            </>,
            <>
              <strong>Agent conversations.</strong> Messages you exchange with Arcus, the treasury
              agent, and the responses it produces.
            </>,
            <>
              <strong>On-chain transfer records.</strong> Transaction hashes, amounts, and wallet
              addresses for testnet deposits and withdrawals you initiate.
            </>,
            <>
              <strong>Technical logs.</strong> Standard request logs (timestamps, request paths,
              status codes) used for reliability and abuse prevention.
            </>,
          ]}
        />
      </>
    ),
  },
  {
    id: 'what-we-do-not-collect',
    heading: 'What we do not collect',
    body: (
      <>
        <DocList
          items={[
            <>No names, email addresses, phone numbers, or postal addresses.</>,
            <>No government identification or KYC documentation.</>,
            <>No private keys or seed phrases; signing always happens inside your own wallet.</>,
            <>No third-party advertising trackers, analytics pixels, or fingerprinting scripts.</>,
          ]}
        />
        <DocNote label="Design principle">
          If a feature can work without a piece of personal data, the Service is built not to ask
          for it.
        </DocNote>
      </>
    ),
  },
  {
    id: 'how-we-use-information',
    heading: 'How we use information',
    body: (
      <>
        <p>We use the data described above exclusively to:</p>
        <DocList
          items={[
            <>Authenticate operators and maintain signed-in sessions.</>,
            <>Operate your treasury: generate, validate, execute, and record proposals.</>,
            <>Verify testnet deposits and process withdrawal requests on-chain.</>,
            <>Enforce security controls: withdrawal caps, emergency pause, and role permissions.</>,
            <>Maintain a tamper-evident audit trail of privileged actions.</>,
            <>Detect abuse, debug failures, and keep the Service reliable.</>,
          ]}
        />
        <p>
          We do not sell, rent, or trade any data, and we do not use your data for advertising or
          profiling.
        </p>
      </>
    ),
  },
  {
    id: 'ai-processing',
    heading: 'AI processing',
    body: (
      <>
        <p>
          Arcus, the treasury agent, is powered by a third-party large-language-model provider.
          When you send a command or question, the text of your message, together with
          non-personal treasury context such as balances, modes, and policy state, is transmitted
          to that provider to generate a response.
        </p>
        <p>
          Agent conversations are subject to rate limits and content bounds to prevent abuse.{' '}
          <strong>Do not include personal, sensitive, or confidential information in messages to
          Arcus</strong>; the agent needs none of it to manage a testnet treasury.
        </p>
      </>
    ),
  },
  {
    id: 'cookies',
    heading: 'Cookies',
    body: (
      <>
        <p>
          The Service sets exactly one cookie: an essential, HTTP-only session cookie created when
          you sign in with your wallet. It contains a random session identifier (no tracking
          data) and is removed when you sign out or when the session expires.
        </p>
        <p>There are no analytics, advertising, or cross-site cookies.</p>
      </>
    ),
  },
  {
    id: 'on-chain-data',
    heading: 'On-chain data is public',
    body: (
      <>
        <p>
          Deposits and withdrawals settle on the Arc Testnet, a public blockchain. Transaction
          hashes, wallet addresses, amounts, and timestamps are permanently visible to anyone
          through a block explorer. This is a property of public blockchains, not something Revo
          controls, and it cannot be deleted by us or by you.
        </p>
      </>
    ),
  },
  {
    id: 'security',
    heading: 'How we protect data',
    body: (
      <>
        <DocList
          items={[
            <>
              <strong>Tenant isolation.</strong> Every treasury is private to the wallet that owns
              it. All reads and writes are scoped server-side to your authenticated session; no
              client-supplied identifier can reach another treasury.
            </>,
            <>
              <strong>Encrypted custody keys.</strong> Private keys for platform-managed treasury
              wallets are sealed with authenticated encryption at rest and are never exposed
              through the API.
            </>,
            <>
              <strong>Tamper-evident auditing.</strong> Privileged actions are recorded in a
              hash-chained audit log, so retroactive modification is detectable.
            </>,
            <>
              <strong>Signature-bound withdrawals.</strong> Funds only leave a treasury toward a
              wallet that has cryptographically proven ownership, within enforced limits.
            </>,
          ]}
        />
      </>
    ),
  },
  {
    id: 'retention',
    heading: 'Data retention',
    body: (
      <>
        <p>
          Treasury records, audit events, and transfer history are retained for as long as the
          Service operates, because they form the operational and security record of your
          treasury. Expired sessions are invalidated and unusable. Because the platform runs on a
          test network, the environment, including stored records, may be reset as part of
          testnet lifecycle events.
        </p>
      </>
    ),
  },
  {
    id: 'your-controls',
    heading: 'Your controls',
    body: (
      <>
        <DocList
          items={[
            <>
              <strong>Sign out at any time:</strong> this invalidates your session immediately.
            </>,
            <>
              <strong>Stop using the Service:</strong> no background collection occurs when you
              are not signed in.
            </>,
            <>
              <strong>Withdraw your testnet funds:</strong> deposited testnet USDC can be
              withdrawn back to the depositing wallet, subject to security limits.
            </>,
          ]}
        />
      </>
    ),
  },
  {
    id: 'changes',
    heading: 'Changes to this policy',
    body: (
      <p>
        We may update this policy as the Service evolves. Material changes will be reflected in
        the version number and effective date at the top of this document. Continued use of the
        Service after a change takes effect constitutes acceptance of the revised policy.
      </p>
    ),
  },
  {
    id: 'contact',
    heading: 'Contact',
    body: (
      <p>
        Questions about this policy can be raised through the operator console. This document
        should be read together with the{' '}
        <a href="terms" className="text-primary hover:underline">Terms of Service</a> and the{' '}
        <a href="risk" className="text-primary hover:underline">Risk Disclaimer</a>.
      </p>
    ),
  },
];

export default function Privacy() {
  return (
    <DocLayout
      code="RVO-LGL-01"
      title="Privacy Policy"
      tagline="What the Revo Treasury platform collects, why it collects it, and the boundaries we hold: no accounts, no trackers, no data sold. Your wallet is your identity."
      sections={sections}
    />
  );
}
